beam.cabal

Cabal only needs the version bounds specified once, which makes things less error prone in the future.

Add missing version bounds, make bounds DRY

---

beam-core/Database/Beam/Schema/Tables.hs

```
Database/Beam/Schema/Tables.hs:28:17: error:
Ambiguous occurrence ‘C’
It could refer to either ‘GHC.Generics.C’,
imported from ‘GHC.Generics’ at Database/Beam/Schema/Tables.hs:61:1-40
or ‘Database.Beam.Schema.Tables.C’,
defined at Database/Beam/Schema/Tables.hs:264:1
```
looks like it was introduced by 0c1ee6992e0d852c303313a7e529a24df9742d62

Fix "Ambiguous Occurrence 'C'"

---

docs/theme/main.html

Should fix the following errors in console and toggling examples
```
tathougies.github.io/:1 Mixed Content: The page at 'https://tathougies.github.io/beam/' was loaded over HTTPS, but requested an insecure script 'http://code.jquery.com/jquery-2.2.4.min.js'. This request has been blocked; the content must be served over HTTPS.
bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery
at bootstrap.min.js:6
tathougies.github.io/:1036 Uncaught ReferenceError: $ is not defined
at tathougies.github.io/:1036
beam.css Failed to load resource: the server responded with a status of 404 ()
```

Use https for fetching jquery dep

---

beam-core/Database/Beam/Query/Combinators.hs

This allows queries like the following to have aggregates in the condition:
```sql
select (case when max(foo) > 5 then 'a' else 'b' end) from generate_series(1,2) foo;
```
``` 
case 
------
b
(1 row)
```

Relax QIf* expressions to allow contexts other than QValueContext.

---

docs/index.md

Just adding some docs to use in a project since beam isn't realeased to stackage yet.
just use the stack file to pull directly from master to whichever commit you
would like.
After that, add beam-core, beam-migrate, and the backend of your choice
[postgres|sqlite] (to your cabal file)

updating docs for installing until released on hackage

---

beam-core/beam-core.cabal

Things appear to work with wider `dlist` bounds. I needed this because `reflex-platform`'s `ghcjs` package set is currently stuck on dlist 7.2.1. If you'd rather not merge this in order to minimize your compatibility "footprint", I can work around it easily on my end. But I figured I'd offer it as a change in case you want it.

Widen dlist lower bound

---

beam-migrate/beam-migrate.cabal

`beam-migrate` builds with base-4.10.0.0, so I increased the version bounds to reflect this

Bumped base version bounds for beam-migrate

---

beam-postgres/Database/Beam/Postgres/PgSpecific.hs

I noticed this trying to insert a jsonb into a table
with debug mode on, I can see the sql generated as
```sql
INSERT INTO "some_table"
("some_jsonb") 
VALUES 
([{"task":"do the other thing"}]::jsonb), ([{"task":"do this other thing"}]::jsonb)
```
```text
*** Exception: SqlError {sqlState = "42601", sqlExecStatus = FatalError, sqlErrorMsg = "syntax error at or near \"[\"", sqlErrorDetail = "", sqlErrorHint = ""}
```
and perusing the [postgres json docs](https://www.postgresql.org/docs/9.6/static/datatype-json.html) I could see that beam is missing the single quotes
```sql
SELECT '{"bar": "baz", "balance": 7.77, "active":false}'::json;
```
I'm using postgres `9.6.5`, and this fixes the errors for me.  Wondering if you can check on your machine?
Also I know there aren't any tests for a …

postgres json[b] needs to be single quoted for postgres to not complain

---

beam-migrate/beam-migrate.cabal

It previously was listed in neither `exposed-modules` nor `other-modules`, but
*was* re-exported through the top-level module `Database.Beam.Migrate`.
Warning was:
```
Warning: The following modules should be added to exposed-modules or other-modules in /Users/judah.jacobson/repos/beam/beam-migrate/beam-migrate.cabal:
- In the library component:
Database.Beam.Migrate.Backend
Missing modules in the cabal file are likely to cause undefined reference errors from the linker, along with other problems.
```
(In this case it seemed to not cause problems because that module only defined
data types.)

Fix warning: export `Database.Beam.Migrate.Backend`.

---

beam-core/Database/Beam/Query/CustomSQL.hs

This makes it possible to write down the type inferred for `customExpr_` expressions.

Export IsCustomExprFn

---

beam-migrate-cli/Database/Beam/Migrate/Tool/Backend.hs

Unpack interpreter errors because `show` mangles newlines etc.

Actually readable interpreter errors

---

beam-postgres/beam-postgres.cabal

Exposed the module `Database.Beam.Postgres.Syntax` so that custom data types can be used in migration.

Expose Syntax module

---

docs/tutorials/tutorial1.md

When scanning the page, it's easier to recognize an instance if it isn't split. Also the associated type declaration threw me off the first time. Not sure where the note should go.

Merged typeclass declaration, added note about data in Table

---

beam-migrate/Database/Beam/Migrate/Simple.hs

So users can access it from other modules. Based off of https://github.com/tathougies/beam/issues/154#issuecomment-373897308.

Export autoMigrate from Database.Beam.Migrate.Simple

---

beam-sqlite/Database/Beam/Sqlite/Migrate.hs

The SQLite migration engine would incorrectly label fields
of type 'TIMESTAMP' as fields of type 'TIME'. This is because
the SQLite type parser is greedy and the 'TIME' parser came first.
This reorders the timestamp and time parser so we get correctly
typed columns

Fix SQLite migration bug

---

beam-core/Database/Beam/Backend/SQL.hs
beam-migrate-cli/Database/Beam/Migrate/Tool/Diff.hs
beam-migrate-cli/Database/Beam/Migrate/Tool/Log.hs
beam-migrate/Database/Beam/Migrate/Log.hs
beam-migrate/Database/Beam/Migrate/Simple.hs

While it is convenient for inference, these dependencies make it impossible to naturally use a monad transformer on MonadBeam.

Remove functional dependencies `be -> m`, `handle -> m` on MonadBeam

---

docs/index.md

I couldn't find any `beam-users` Google Group, but instead the `beam-discussion` one. This might help newcomers (as me) to end up in the right place.

Added beam-discussion google link

---

beam-core/Database/Beam/Query/Ord.hs
beam-postgres/Database/Beam/Postgres.hs
beam-postgres/Database/Beam/Postgres/Syntax.hs
beam-postgres/beam-postgres.cabal

Exports the Postgres run* functions and adds Tagged type instances for the new equality bits.
Closes #215

Fix beam postgres 0.7

---

docs/tutorials/tutorial1.md

The command:
```
$ stack repl --package beam-core --package beam-sqlite --package sqlite-simple
```
from the tutorial gives the following error:
```
⋊> ~ stack repl --package beam-core --package beam-sqlite --package sqlite-simple                                                                                       14:38:15
Error: While constructing the build plan, the following exceptions were encountered:
In the dependencies for beam-sqlite-0.3.2.0:
beam-migrate must match >=0.3 && <0.4, but the stack configuration has no specified version  (latest matching version is 0.3.1.0)
needed since beam-sqlite is a build target.
Some different approaches to resolving this:
* Consider trying 'stack solver', which uses the cabal-install solver to attempt to find some working build configuration. …
```

Add beam-migrate package for the tutorial

---

CONTRIBUTORS
beam-core/Database/Beam/Schema/Tables.hs
beam-core/test/Database/Beam/Test/Schema.hs

Generalize the deriving mechanism so the class `Beamable` can be derived
even for those types containing parametrized `Beamable` fields.
For example, the following code does not currently compile, but it would under this PR:
```
module Foo where
import Database.Beam
data FooT inner f = Foo 
{ _foo  :: C f Int
, _moo  :: C f Int
, _inn1 :: inner f
} deriving(Generic)
instance (Beamable inner) => Beamable (FooT inner)
```
This is a fix for issue https://github.com/tathougies/beam/issues/222

derivable parametrized beams

---

beam-postgres/Database/Beam/Postgres/Migrate.hs

`getDbConstraints` must filter out dropped columns when gathering info for column checks. Otherwise the query could result in something like below. Tested on 9.6.8.
```
attname            | atttypid | atttypmod | attnotnull |         format_type
------------------------------+----------+-----------+------------+-----------------------------
id                           |       20 |        -1 | t          | bigint
(...)
........pg.dropped.7........ |        0 |        -1 | f          | -
........pg.dropped.8........ |        0 |        -1 | f          | -
........pg.dropped.9........ |        0 |        -1 | f          | -
```

Ignore dropped columns in getDbConstraints

---

beam-migrate/Database/Beam/Migrate/Generics/Tables.hs

Got some unexpected failed predicates from `verifySchema` where beam would insist it wants `Double` to be stored as `real`. [Docs](https://www.postgresql.org/docs/current/static/datatype-numeric.html) suggest this should be `double precision`.
Not quite sure how much breakage this could cause so just throwing it out here for now.

Fix default SQL type for Double

---

beam-postgres/Database/Beam/Postgres.hs
beam-postgres/Database/Beam/Postgres/PgSpecific.hs

I noticed this appeared missing from the Postgres specific package.
I admittedly haven't tested this locally (yet) so there could be syntax bugs, missing constraints, etc. but I figured I'd gone far enough without some feedback (maybe too far?).
I'm also pretty sure this doesn't support beam-migrate yet. I'm not familiar with that functionality at all but I'd be willing to add that support to this PR with a bit of guidance.
When you get a chance, let me know what you think of the general design or any questions/comments you have.
Next chance I get to work on this I'll confirm some basic schema definitions and queries, assuming you don't have any fundamental design change requests to take care of first.

Postgres Range type support

---

beam-core/Database/Beam.hs
beam-core/Database/Beam/Backend.hs
beam-core/Database/Beam/Backend/SQL.hs
beam-core/Database/Beam/Backend/SQL/BeamExtensions.hs
beam-core/Database/Beam/Backend/SQL/Builder.hs
beam-core/Database/Beam/Backend/URI.hs
beam-core/Database/Beam/Query.hs
beam-migrate-cli/Database/Beam/Migrate/Tool/Diff.hs
beam-migrate-cli/Database/Beam/Migrate/Tool/Log.hs
beam-migrate-cli/Database/Beam/Migrate/Tool/Registry.hs
beam-migrate-cli/Database/Beam/Migrate/Tool/Schema.hs
beam-migrate-cli/Database/Beam/Migrate/Tool/Status.hs
beam-migrate/Database/Beam/Migrate/Backend.hs
beam-migrate/Database/Beam/Migrate/Log.hs
beam-migrate/Database/Beam/Migrate/Simple.hs
beam-postgres/Database/Beam/Postgres/Connection.hs
beam-postgres/Database/Beam/Postgres/Migrate.hs
beam-sqlite/Database/Beam/Sqlite/Connection.hs
beam-sqlite/Database/Beam/Sqlite/Migrate.hs
docs/about/faq.md
docs/tutorials/tutorial1.md
docs/user-guide/backends.md
docs/user-guide/queries/relationships.md
docs/user-guide/queries/select.md

This is a breaking change, so feel free to push back. (Although it can be made compatible at the expense of a bit of cleanliness.)
My concrete motivation for splitting these is that I want to be able to define `MonadBeam` instances to run Beam queries in other SQL libraries in order to ease the conversion of an application to Beam. In this context, `withDatabase` doesn't always make sense (especially returning raw `IO`).
More abstractly, I don't think it makes sense to group the constructors/methods of a monad class with its elimination functions. (Consider in `mtl` the elimination functions don't belong to classes at all.)
If you think this approach is worth considering, we should probably also think about the interface to `MonadWithDatabase` (name also subject to debate). I think really …

Remove `withDatabase` and `withDatabaseDebug` from `MonadBeam`.

---

beam-postgres/Database/Beam/Postgres/Full.hs
beam-postgres/Database/Beam/Postgres/Migrate.hs
beam-postgres/Database/Beam/Postgres/Syntax.hs

The build of `beam-postgres` failed for me with GHC 8.4.2 because of Semigroup/Monoid issues.  What do you think of this approach, using newtype deriving with an intermediate type?  With these changes I'm able to build and install.

More GHC 8.4 compatibility.

---

docs/tutorials/tutorial1.md

I fixed some small errors when going through the first tutorial.
Adding `MultiParamTypeClasses` in GHCI is only necessary when following the tutorial in GHCI past the "Defining our database" headline. However, I doubt anyone is still using GHCI at this point, because you can't c&p multiline definitions into GHCI, so many will probably already give up when trying to define `UserT` (at least I did).
Maybe it would be easier to follow when telling people to create a file (`Main.hs`) and load that into GHCI (`:l Main` / `:r` + functions `insertUsers`, `query1`, ...)?

Tutorial 1 fixes

---

docs/user-guide/expressions.md

a very simple change: automaticall -> automatically

correct typo

---

beam-postgres/Database/Beam/Postgres/Connection.hs

Fix bug in withPgDebug's stepProcess.
In case of a successful parse we should always pass a Just to next.

Fix stepProcess

---

beam-core/Database/Beam/Query/Combinators.hs

I've been using this as a `<|>` equivalent (specialized to `Maybe`) for "get the first non-null" behavior.
`ghci` actually inferred a more general type, but I'm not familiar enough with Beam to tell which is a better fit:
```haskell
(SqlJustable a2 (QGenExpr ctxt syntax s y), SqlDeconstructMaybe syntax a1 a2 s) =>
a1 -> QGenExpr ctxt syntax s y -> QGenExpr ctxt syntax s y
```

Add '<|>.' operator

---

beam-postgres/Database/Beam/Postgres/Migrate.hs

This fixes the following bug: when running migrations on a schema other than "public" (eg. when running as a non-admin user),  `bringUpToDate` will create the `beam_version` table on first run, but on subsequent runs it will fail to find that table, try to create it again, and fail to do that because the table already exists.

Examine all current schemas when generating DB constraints

---

beam-postgres/Database/Beam/Postgres/PgSpecific.hs
beam-postgres/Database/Beam/Postgres/Syntax.hs

When attempting to use `array_` I found myself unable to get it to type check. The problem appeared to be the hard requirement of `PgArrayValueContext` for the expressions in the `Foldable`. Looking through the docs, it appears to be impossible to construct a value/expression with this context. On the other hand, `PgIsArrayContext :: Constraint` seems to already limit `context` to the appropriate contexts (Value, Aggregate, Window).
I think the change below is correct as it limits possible contexts to those that can exist in an array and makes `array_` keeps the context of the subexpression.
The `Vector` `HasValueSyntax` instance needed to reference array literals appeared to be missing.
I exported `defaultPgValueSyntax` as this was the first thing I attempted to reach for to define a …

Pg array improvements

---

CONTRIBUTORS
beam-sqlite/Database/Beam/Sqlite.hs
beam-sqlite/Database/Beam/Sqlite/SqliteSpecific.hs
beam-sqlite/Database/Beam/Sqlite/Syntax.hs
beam-sqlite/beam-sqlite.cabal

Add the SQLite [group_concat](https://www.sqlite.org/lang_aggfunc.html#groupconcat) function.
I pretty much just copied the [implemention](https://github.com/tathougies/beam/blob/d6b45713de886e7cfbd019eafb86496cc99182dc/beam-postgres/Database/Beam/Postgres/PgSpecific.hs#L1061) of the PG `string_agg` function.
Differences to `pgStringAgg` 
1. Input constraint changed from `IsSqlExpressionSyntaxStringType` to `HasSqlValueSyntax` 
The reason for that is simply that I need to join an `INTEGER` column in my project. I think a better solution might be to use `cast_`. I couldn't find an implementation of `cast_` though, just `caseE`. Is this a dealbreaker? I guess that e.g. joining `BLOB` really doesn't make sense. Could I constrain the function to take string and number types somehow?
2. Split …

Add SQLite group_concat function

---

CONTRIBUTORS
beam-migrate/Database/Beam/Migrate/SQL/Tables.hs

While running this simplified example
```
data UserDB f = UserDB {
_uDbUser  :: f (TableEntity UserT)
} deriving Generic
data UserT f = User { _uName :: Columnar f String
, _uAge  :: Columnar f Word32
} deriving Generic
instance Beamable UserT
instance Table UserT where
data PrimaryKey UserT f = UserPrimKey deriving Generic
primaryKey User{..} = UserPrimKey
instance Database Sqlite UserDB
instance Beamable (PrimaryKey UserT)
testSQlite :: IO ()
testSQlite = do
conn <- Sqlite.open ":memory:"
runBeamSqliteDebug putStrLn conn $
executeMigration runNoReturn initialMigration
Sqlite.close conn
initialMigration =
UserDB <$> createTable "users"
(User (field "name" (DataType (varCharType Nothing Nothing)) notNull)
(field "age" (DataType intType) notNull)
)
```
I noticed a runtime error 
``` …
```

Fix createTable when there is no Primary Key

---

.gitlab-ci.yml

- runs `./build-docs.sh` instead of `./builddocs.sh`

Fix typo in Gitlab CI config

---

beam-core/Database/Beam/Backend/SQL/BeamExtensions.hs
beam-core/Database/Beam/Query/Internal.hs
beam-postgres/Database/Beam/Postgres.hs
beam-postgres/Database/Beam/Postgres/Full.hs

I'd like to add upsert support for `beam-sqlite` and this seemed like a good opportunity to abstract across backends. Before I finish that I figured I'd get this out to hear your thoughts on the design.

Add HasInsertOnConflict class for postgres/sqlite-like upsert support

---

docs/tutorials/tutorial3.md

Because of this missing newline, this part currently looks like this on `github.io`:

A small typo that messes up Markdown

---

docs/user-guide/expressions.md

The note added in https://github.com/tathougies/beam/pull/361 is no longer needed as `in_` on primary keys is supported as of https://github.com/tathougies/beam/pull/384.

Remove out of date note about `in_` on primary keys which is now supported

---

beam-core/Database/Beam/Query/Combinators.hs
beam-core/Database/Beam/Query/Ord.hs
beam-core/Database/Beam/Schema/Tables.hs

Removing this use of `undefined` seems to make it possible to use strict fields for table and database types. Splitting `WithConstraint` also improves conceptual clarity and type safety by distinguishing cases where it is used just to carry around a constraint, and cases where the constrained value is carried too.

Split WithConstraint into versions with/without value and remove partiality

---

beam-migrate-cli/Database/Beam/Migrate/Tool/Migrate.hs
beam-migrate/Database/Beam/Migrate/Backend.hs

Otherwise the migration, which can fail, cannot be run.

SomeBeamMigrationBackend needs MonadFail

---

beam-core/Database/Beam/Query/Combinators.hs

I use these sort of combinators often in code that tries to abstracts over whether things are being run in haskell or the database, e.g.:
```haskell
someComputation' bool' x = bool'
(thisComputation x)
(thatComputation x)
(somePredicate x)
someComputation = someComputation' bool 
someComputation_ = someComputation' bool_
```

Add haskell-style conditionals

---

beam-postgres/Database/Beam/Postgres/Migrate.hs

Only detect primary-keys of visible tables in beam-postgres

---

beam-postgres/Database/Beam/Postgres/Full.hs

It looks like these functions got moved to a different module where everything was exported, then moved back but not added to the the exports for this module.

Re-export a few missing functions

---

beam-postgres/Database/Beam/Postgres.hs
beam-postgres/Database/Beam/Postgres/Connection.hs
beam-postgres/Database/Beam/Postgres/Debug.hs
beam-postgres/Database/Beam/Postgres/Migrate.hs

That allows to override `getDbConstraints` in migration backend.

Add liftIOWithHandle :: (Connection -> IO a) -> Pg a

---

docs/user-guide/queries/select.md

It looks like beam actually supports up to 8-tuples.
https://github.com/tathougies/beam/blob/master/beam-core/Database/Beam/Query/Types.hs#L34

Update docs with latest supported size of tuples

---

beam-core/Database/Beam/Backend/SQL.hs
beam-core/Database/Beam/Backend/SQL/Row.hs
beam-postgres/Database/Beam/Postgres/Types.hs

This allows Tagged's phantom type to be of kind `Symbol`.
Context: https://haskell.zettel.page/047d9f68.html

Add PolyKinds to modules deriving for Data.Tagged

---

beam-postgres/Database/Beam/Postgres/PgSpecific.hs

This one really confused me for a while. I was wondering where in the database was null being used (all my fields had `NOT NULL` constraint). Turns out the `FromField` instance for PgJSONB (and PgJSON) ignores aeson errors and reports them (incorrectly) as "UnexpectedNull". 
This PR fixes that by:
a) throwing UnexpectedNull only when the argument value is Nothing
b) using aeson's `eitherDecodeStrict` to report the error back to the library user

postgres: Report json decoding errors

---

beam-migrate/Database/Beam/Migrate/Generics/Tables.hs
beam-postgres/Database/Beam/Postgres/Types.hs

This branch includes three commits:
* Support `SqlSerial Int16`, `SqlSerial Int32`, and `SqlSerial Int64`
* Change the representation of Int16 to be SMALLINT
* Change the representation of Int to be BIGINT when it is 64 bits wide (but keep it as INTEGER when it is 32 bits wide)
I'm not entirely sure whether the latter two are actually a good idea - personally, I wouldn't use `Int` at all for SQL.  However, it seemed more correct to do it this way.  Let me know if you'd prefer I send these PRs separately or dice it up in some other way.

Improve integer size translations

---

beam-postgres/Database/Beam/Postgres/Full.hs
beam-sqlite/Database/Beam/Sqlite/Connection.hs

When I originally wrote these I believe I was unaware that these can be `newtype`s.

Use newtype for BeamHasInsertOnConflict data family instances

---

beam-core/beam-core.cabal
beam-migrate-cli/beam-migrate-cli.cabal
beam-migrate/beam-migrate.cabal
beam-postgres/beam-postgres.cabal
beam-sqlite/beam-sqlite.cabal

Breaking changes in `beam-core`: #413 (unlikely to break anyone in practice).
Breaking changes in `beam-migrate`: #329.
Breaking changes in `beam-postgres`: #329, #347 and associated PRs.
Breaking changes in `beam-sqlite`: #435.

Bump major version numbers

---

beam-postgres/Database/Beam/Postgres/Migrate.hs
beam-postgres/test/Database/Beam/Postgres/Test/Migrate.hs

Currently `verifySchema` doesn't pick up extensions, and thus fails if `CheckedDatabaseSettings` specifies any.

Add postgres extensions to database predicates

---

beam-core/Database/Beam/Query/Aggregate.hs
beam-core/Database/Beam/Query/Combinators.hs
beam-core/Database/Beam/Query/Extensions.hs
beam-core/test/Database/Beam/Test/SQL.hs

This should remove all SQL-internal uses of `Int` in beam-core (#496). Rather than introducing a type family for the cardinality type for a backend, I extended the existing pattern of using `Integral`, even though it's in general less safe.

Use Integral for SQL Int values in beam-core

---

beam-postgres/Database/Beam/Postgres/PgCrypto.hs
beam-postgres/Database/Beam/Postgres/PgSpecific.hs

This is the first step of #496.
Relevant documentation:
* `UNNEST ... WITH ORDINALITY`: https://www.postgresql.org/docs/12/queries-table-expressions.html
* JSON functions: https://www.postgresql.org/docs/current/functions-json.html
* pgcrypto: https://www.postgresql.org/docs/current/pgcrypto.html

Use explicitly sized integer types for Postgres-specific functions

---

beam-postgres/Database/Beam/Postgres/Extensions/Internal.hs
beam-postgres/Database/Beam/Postgres/Extensions/UuidOssp.hs
beam-postgres/Database/Beam/Postgres/PgCrypto.hs
beam-postgres/beam-postgres.cabal
beam-postgres/test/Database/Beam/Postgres/Test/Select.hs

As of #488 extensions are picked up by `backendGetDbConstraints`, so it becomes more useful to have them predefined.

Add Postgres extension definition for uuid-ossp

---

beam-core/Database/Beam/Backend/SQL/Builder.hs
beam-postgres/Database/Beam/Postgres/Syntax.hs
beam-sqlite/Database/Beam/Sqlite/Syntax.hs

`DOUBLE` is not a valid SQL 92 data type, and Postgres completely rejects it. SQLite would misleadingly accept it with `REAL` affinity instead of `NUMERIC` which is what you might expect if a precision were specified.

Fix emitting of SQL 92 DECIMAL type

---

beam-core/Database/Beam/Query.hs

Fixes some warnings/style issues introduced in #464.

Fix double export and tab characters in Database.Beam.Query

---

beam-postgres/Database/Beam/Postgres/PgSpecific.hs

[These functions](https://www.postgresql.org/docs/current/functions-json.html#FUNCTIONS-JSONB-OP-TABLE) only work with `jsonb` and not `json`.

Fix the types of some Postgres operators that only work with jsonb

---

beam-core/Database/Beam/Query.hs
beam-core/Database/Beam/Query/Ord.hs
beam-postgres/test/Database/Beam/Postgres/Test/Select.hs
beam-sqlite/Database/Beam/Sqlite/Connection.hs
beam-sqlite/test/Database/Beam/Sqlite/Test.hs
beam-sqlite/test/Database/Beam/Sqlite/Test/Select.hs

I think when I wrote #384 I tried it manually with one multi-column row value, or multiple single-column rows, both of which SQLite just happens to support with the expected syntax. With multiple multi-column rows however, it's required to turn the list into a sub-query with `VALUES`.

Fix SQLite IN with row values and add tests

---

beam-core/Database/Beam/Backend/Internal/Compat.hs
beam-core/Database/Beam/Backend/SQL/AST.hs
beam-core/Database/Beam/Backend/SQL/Builder.hs
beam-core/Database/Beam/Backend/SQL/SQL92.hs
beam-core/Database/Beam/Query/Combinators.hs
beam-core/Database/Beam/Query/CustomSQL.hs
beam-core/beam-core.cabal
beam-core/test/Database/Beam/Test/SQL.hs
beam-core/test/Database/Beam/Test/Schema.hs
beam-migrate/Database/Beam/Haskell/Syntax.hs
beam-migrate/Database/Beam/Migrate/Generics/Tables.hs
beam-migrate/Database/Beam/Migrate/Log.hs
beam-migrate/Database/Beam/Migrate/Simple.hs
beam-postgres/Database/Beam/Postgres/Syntax.hs
beam-postgres/Database/Beam/Postgres/Types.hs
beam-postgres/examples/Pagila/Schema/CustomMigrateExample.hs
beam-postgres/examples/Pagila/Schema/V0001.hs
beam-postgres/examples/Pagila/Test.hs
beam-postgres/test/Database/Beam/Postgres/Test/DataTypes.hs
beam-postgres/test/Database/Beam/Postgres/Test/Marshal.hs
beam-sqlite/Database/Beam/Sqlite/Connection.hs
beam-sqlite/Database/Beam/Sqlite/Syntax.hs

Fixes #496. It's possible I missed some, but all instances for `Int` and `Word` should now be replaced with a helpful custom type error.

Remove instances for ambiguously sized integers

---

beam-core/Database/Beam/Query/Combinators.hs

Currently the docs look like "Synonym for `clause >>= x -> guard_ (mkExpr x)>> pure x`".

Escape backslashes in Haddock

---

beam-sqlite/ChangeLog.md
beam-sqlite/Database/Beam/Sqlite/Connection.hs
beam-sqlite/Database/Beam/Sqlite/Syntax.hs
beam-sqlite/beam-sqlite.cabal
beam-sqlite/test/Database/Beam/Sqlite/Test/Select.hs

runInsertReturningList on Sqlite does a bit of a dance to get the results out. The temporary table has to be created using a `SELECT *` so that type information which `beam-core` does not have available is propagated to the new temporary table. However, this can cause deserialization issues if the fields in SQLite are not in the same order as in Haskell. This is fixed by ensuring we `SELECT` from the temporary table using an explicit projection.

Fix beam-sqlite runInsertReturningList

---

beam-migrate/Database/Beam/Migrate/SQL/Tables.hs

This is minor, but I needed this in some type signatures. It was because I'm adding extra type parameters to my tables and using type families in them, so the compiler can't always see the real type and infer `IsNotNull`.

Expose IsNotNull typeclass

---

beam-postgres/Database/Beam/Postgres/Connection.hs

Tentative fix for #544.
We currently [manually free](https://github.com/haskell-beam/beam/blob/4d30ed45b16c41be26cb6301e9033c99379bf2d9/beam-postgres/Database/Beam/Postgres/Connection.hs#L232) the Postgres result object, and it seems that at least for `PgJSONB`, but likely also `PgJSON`, `Text, `ByteString`, etc. it's possible a slice of the underlying bytestring can outlive the result and cause a use-after-free bug.
`postgresql-simple` apparently also [copies](http://hackage.haskell.org/package/postgresql-simple-0.6.4/docs/Database-PostgreSQL-Simple-FromField.html#v:fromField) the data instead of letting GC handle the `Result`, which would be the other possible fix.

Copy Postgres result data when reading rows

---

release.nix

I wasn't aware of `recurseForDerivations` before but it makes it a bit simpler not having to construct one giant map for all the built derivations.

Simplify release.nix

---

beam-core/Database/Beam/Query/Combinators.hs

As we all know, specifying the ordering (`ASC`/`DESC`) in an SQL `ORDER BY` clause is optional. Consequently, when using beam's `orderBy_`, it's natural to incorrectly let the function passed as the first argument return just the field that we wish to order by (in ascending order). When mistakenly doing this, the user is met with the following error message from GHC:
```
• No instance for (SqlOrderable
Pg.Postgres
(QGenExpr
QValueContext Pg.Postgres (QNested QBaseScope) Path.UTCTime))
arising from a use of ‘orderBy_’
```
Even though I've used beam for quite a while, I still occasionally do this. A more telling error message would be very helpful in leading me in the right direction. At first glance, it looks like the problem relates to a specific data type not having a well-defined …

orderBy_: improve error on missing asc_/desc_

---

beam-migrate/Database/Beam/Migrate/Simple.hs

If Postgres decides to return migration log entries in an unexpected order, `bringUpToDateWithHooks` will loop forever. I'm not sure _why_ it loops, but the query should have an `order by` anyway.

Order log entries when verifying migration status

---

beam-postgres/Database/Beam/Postgres/Conduit.hs

In addition to bringing compatability with the MonadBaseControl-free
conduit library, the new variants are much more composable (e.g. they
can be combined with servant's streaming capabilities).

Postgres.Conduit: Add streaming variants directly in a MonadResource

---

beam-core/ChangeLog.md
beam-core/beam-core.cabal
beam-migrate/ChangeLog.md
beam-migrate/beam-migrate.cabal
beam-postgres/ChangeLog.md
beam-postgres/beam-postgres.cabal
beam-sqlite/ChangeLog.md
beam-sqlite/beam-sqlite.cabal

This is a retroactive release (branched off 77c44566d641a38d7df9b15cac5bb8de895e1e36) of bug fixes and backwards compatible feature additions for each package.
Soon we'll do another release off master including breaking changes.
Fixes #565.

Release beam-core 0.9.1.0; beam-migrate, beam-postgres, beam-sqlite 0.5.1.0

---

beam-postgres/Database/Beam/Postgres/Syntax.hs
beam-postgres/test/Database/Beam/Postgres/Test/Select.hs

Append `::uuid` to Postgres UUID value syntax

---

beam-postgres/Database/Beam/Postgres/Conduit.hs

Fixes #596 
Sadly I don't have a good reproducer for serialization errors, but I'm confident that this is the correct fix, based on the fact the error message had `Postgres error:` which only occurs on the line below. The three matches correspond to how postgresql-simple uses `throwResultError`.

Postgres.Conduit: throw SqlError when row is error

---

beam-core/Database/Beam/Query/Operator.hs
beam-postgres/Database/Beam/Postgres/PgSpecific.hs

Some experience with #562 suggests that it causes too much breakage since often the haystack string is static and then it needs a type annotation since it can't just unify with the needle.
I'm not a big fan of just appending `'` so these are hopefully just placeholder names until I can think of something not too clunky.

Make variants for heterogeneous like_/similarTo_/ilike_ and restore originals

---

nix/lib.nix

Follow up to #617. This makes sure that the compatibility CPP works.
It looks like `aeson_2_0_1_0` from the package set has some extra fixes that aren't picked up with just `pinHackageVersions`, which is why that isn't used.

Test aeson 2.0 build in CI

---

beam-postgres/Database/Beam/Postgres/Syntax.hs

bool_any does not actually exist. Somehow this hasn't been noticed until now

beam-postgres: bool_any -> bool_or

---

beam-core/Database/Beam/Query/Combinators.hs

This allows ghc-9.4 to infer the types properly. 
This PR doesn't make beam fully compatible with ghc-9.4 as some dependency bumps are still required.

Fix compilation with ghc-9.4

---

beam-core/Database/Beam/Schema/Tables.hs
beam-core/beam-core.cabal
beam-core/test/Database/Beam/Test/Schema.hs
docs/user-guide/databases.md

This allows embedding databases in one another. Useful to separate out large databases.

allow database embedding

---

beam-core/Database/Beam/Backend/SQL/Row.hs
beam-core/Database/Beam/Query/CTE.hs
beam-core/Database/Beam/Schema/Lenses.hs
beam-core/Database/Beam/Schema/Tables.hs
beam-migrate/Database/Beam/Migrate/SQL/Tables.hs
beam-migrate/Database/Beam/Migrate/Simple.hs
beam-migrate/Database/Beam/Migrate/Types/CheckedEntities.hs

Import changes to build with GHC 9.6.  This patch serves my purposes for now, but if you need to do things differently to preserve backwards compatibility, feel free to adapt as necessary.

Build with GHC 9.6

---

beam-core/beam-core.cabal
beam-migrate/beam-migrate.cabal
beam-postgres/beam-postgres.cabal
beam-sqlite/beam-sqlite.cabal

This is a small PR to loosen some version bounds

Version bound updates

---

beam-core/Database/Beam/Schema/Tables.hs

In the documentation example of the `withDbModification` function, the `modifyTable` function was used, but it has been deprecated. Additionally, the closing parenthesis was missing.
I modified the example to use `setEntityName` and `modifyTableFields` as recommended.
Do let me know, if any changes are required. Thanks!
@kmicklas

Changed documentation example of withDbModification function.

---

beam-postgres/Database/Beam/Postgres/Connection.hs

I was getting `ColumnTypeMismatch` errors and finding them to be pretty opaque if you don't know what column is causing the problem.
It turns out the [Postgres error types](https://hackage.haskell.org/package/postgresql-simple-0.7.0.0/docs/Database-PostgreSQL-Simple.html#t:ResultError) have an `errSQLField` which is useful to expose in the error message.

Improved error for ColumnTypeMismatch

---

beam-core/Database/Beam/Query/SQL92.hs

A WHERE clause in a query is meaningful even if there are no input tables. It makes the difference between there being 0 or 1 results. We therefore should not drop guards when building queries.
See #667.

Fix building queries with WHERE in the absence of FROM.

---

beam-core/Database/Beam/Backend/SQL/Row.hs
beam-core/Database/Beam/Schema/Lenses.hs
beam-core/Database/Beam/Schema/Tables.hs

`beam` relies very heavily on GHC generics, but the standard GHC generic instances are not appropriate for all use cases (motivating example in this case being [`large-records`](https://hackage.haskell.org/package/large-records)). Fortunately, the way GHC generics is set up allows us to use non-standard representations, _provided_ that we can then define additional instances for whatever generic classes are necessary. The [`beam-large-records`](https://github.com/well-typed/beam-large-records) library provides integration for `large-records` with `beam-core`, by providing these additional instances, but this does mean that the generic classes must be _exported_ from `beam-core` so that additional instances can be provided. This commit adds these exports.

Export generic classes

---

.github/workflows/build.yaml

This pull request changes the CI pipeline to use GitHub actions without Nix

CI without nix

---

docs/schema-guide/migrations.md

`beam-migrate` CLI tool has been deleted: https://github.com/haskell-beam/beam/pull/684

document `beam-migrate` as a dependency rather than an executable

---

beam-postgres/examples/src/Pagila/Schema/V0002.hs

This PR improves the `V0002` example migration to include a demo of `alterTable` and `addColumn`.
The example already demonstrated the `preserve` function but not these two other functions.
Now the `V0002` migration additionally adds a `salary` field to `Staff`.
Here is the addition to the migration, rendered to SQL:
```
SQL command type: PgCommandTypeDdl
SQL script: 
ALTER TABLE "staff" ADD COLUMN "salary" SMALLINT DEFAULT 100 NOT NULL
```
Printing this depends on https://github.com/haskell-beam/beam/pull/732

demonstrate `alterTable` and `addColumn` in example migration

---

beam-sqlite/ChangeLog.md
beam-sqlite/Database/Beam/Sqlite/Connection.hs
beam-sqlite/beam-sqlite.cabal

This PR removes `beam-sqlite`'s direct dependence on either the `unix` or `windows` package, which should allow to build `beam-core` and `beam-sqlite` on a wider variety of platforms.
Fixes #738  
Before merging, I want to at least manually check that `beam-sqlite` can be compiled using the WASM backend

Remove direct dependence of `beam-sqlite` on platform-specific packages

---

beam-postgres/ChangeLog.md
beam-postgres/Database/Beam/Postgres/Types.hs
beam-postgres/test/Database/Beam/Postgres/Test/Marshal.hs

This pull request fixes a small conversion error where querying `Nothing` from a column of type `Maybe (Vector a)` would return `Just []` instead of `Nothing`.
Fixes #692

Fix a marshalling error for columns of type `Maybe (Vector a)`

---

beam-postgres/ChangeLog.md
beam-postgres/Database/Beam/Postgres/Syntax.hs
beam-postgres/test/Database/Beam/Postgres/Test/Marshal.hs

This pull request adds the ability to migrate Postgres' Array types.
Note that the mechanism by which this is done is still unsafe; if trying to migrate to an array type whose elements are unsupported (i.e. array OIDs that [don't exist here](https://hackage.haskell.org/package/postgresql-simple-0.7.0.0/docs/Database-PostgreSQL-Simple-TypeInfo-Static.html)), then the migration will result in a runtime error rather than a compile time error.
Breaking changes would have to be made to get compile-time safety of array migrations. 
Fixes #354

Support Postgres array migrations

---

beam-core/Database/Beam/Backend/SQL/Types.hs

Helps with QuickCheck on datatypes built on top of these built-in types

provide `Generic` instances for `...SQL.Types`

---

.gitignore
beam-migrate/Database/Beam/Migrate/Backend.hs
beam-migrate/Database/Beam/Migrate/Serialization.hs
beam-postgres/Database/Beam/Postgres/Migrate.hs
beam-sqlite/Database/Beam/Sqlite/Migrate.hs

After several years, I've finally started working on a tool for beam migrations. I'll start a new repository for my tool, but there are some pieces missing from upstream beam that would be necessary for any migrations tool.
The key change here is adding a function to each backend to execute arbitrary SQL. This is necessary for any tool that allows running arbitrary migration scripts stored as backend-specific SQL.
The other major change is proper support for backend-agnostic transactions and proper connection handling.
All these changes are necessary for any migrations frontend, not just my tool.

Updates to migration backends

---

beam-sqlite/Database/Beam/Sqlite/Migrate.hs
beam-sqlite/beam-sqlite.cabal

Looks like my old changes were wrong. `sqlite-simple` doesn't offer any way to run multi-line SQL scripts. This is from the C `sqlite` library's `exec` function, which is only exposed in `direct-sqlite`.

Proper support for multi-line migration scripts in sqlite

---

beam-core/Database/Beam/Schema/Tables.hs
beam-migrate/Database/Beam/Migrate/Backend.hs
beam-migrate/Database/Beam/Migrate/Types.hs
beam-migrate/Database/Beam/Migrate/Types/CheckedEntities.hs

This adds convenience lenses and accessors for various schema entities, and strictifies some lenses. This is particularly geared towards migrations.

Add convenience accessors

---

beam-sqlite/Database/Beam/Sqlite.hs
beam-sqlite/Database/Beam/Sqlite/Migrate.hs
beam-sqlite/Database/Beam/Sqlite/Syntax.hs

These functions make it easier to write custom data types for SQLite. SQLite is lax with how types are specified, so this is useful if you want to use custom type names for custom haskell data types. Will add documentation.

Convenience functions for custom data types in SQLite

---

docs/tutorials/tutorial2.md
docs/tutorials/tutorial3.md

This PR updates the documentation regarding lens generation to reflect the extra pattern matches that appear to be necessary with newer versions of GHC (as described in [#659](https://github.com/haskell-beam/beam/issues/659) and [#664](https://github.com/haskell-beam/beam/issues/664)).

Update lens generation documentation

---

beam-postgres/Database/Beam/Postgres/PgSpecific.hs
beam-postgres/test/Database/Beam/Postgres/Test/Select.hs

Add Postgres array functions: append, prepend, remove, replace, shuffle, sample, and to_string with tests

Postgres Array functions
