CHANGELOG.md, beam.cabal, src/Database/Beam.hs, src/Database/Beam/Backend.hs, src/Database/Beam/Internal.hs, src/Database/Beam/Query.hs, src/Database/Beam/Query/Combinators.hs, src/Database/Beam/Query/Internal.hs, src/Database/Beam/Query/Types.hs, src/Database/Beam/SQL.hs, src/Database/Beam/SQL/Types.hs, src/Database/Beam/Schema/Fields.hs, src/Database/Beam/Schema/Lenses.hs, src/Database/Beam/Schema/Tables.hs
* Add version bounds
* Add a basic changelog
* Relax upper bound for base to allow building with GHC 8.0
* Fix many GHC warnings (still about 20 left for ~~someone else~~ an eager contributor to fix)
* Move from the deprecated ErrorT to ExceptT
If these changes are too monolithic for you, I can split them up in more granular PRs, just ask me.
=> Update version bounds for GHC 8.0 and fix some warnings

beam-core/Database/Beam/Query/Combinators.hs, beam-core/Database/Beam/Query/Internal.hs, beam-core/test/Database/Beam/Test/SQL.hs
=> Allow referencing the current value of a field in updates

beam-core/Database/Beam/Backend/Types.hs
=> Fixed bug in valuesNeeded implementation for tuples

beam-migrate/Database/Beam/Migrate/Checks.hs, beam-migrate/Database/Beam/Migrate/Diff.hs, beam-migrate/Database/Beam/Migrate/Resolvers.hs, beam-migrate/Database/Beam/Migrate/SQL/SQL92.hs, beam-migrate/Database/Beam/Migrate/SQL/Tables.hs, beam-migrate/Database/Beam/Migrate/SQL/Types.hs, beam-migrate/Database/Beam/Migrate/Tool.hs, beam-migrate/Database/Beam/Migrate/Tool/Types.hs, beam-migrate/Database/Beam/Migrate/Types.hs, beam-migrate/beam-migrate.cabal, beam-migrate/tools/Migrate.hs, beam-postgres/Database/Beam/Postgres.hs, beam-postgres/Database/Beam/Postgres/Migrate.hs, beam-postgres/Database/Beam/Postgres/Syntax.hs, beam-postgres/Database/Beam/Postgres/Types.hs, beam-postgres/examples/Pagila/Schema/V0001.hs, beam-postgres/examples/Pagila/Schema/V0002.hs
=> Emit default instead of NULL for Auto Nothing in postgres

beam-core/Database/Beam/Backend/Types.hs
This permits deriving json instances...
=> Derive generic for Auto

beam-core/Database/Beam/Backend/SQL/AST.hs, beam-core/Database/Beam/Backend/SQL/Builder.hs, beam-core/Database/Beam/Backend/SQL/SQL92.hs, beam-core/Database/Beam/Query.hs, beam-core/Database/Beam/Query/Ord.hs, beam-postgres/Database/Beam/Postgres/Syntax.hs, beam-sqlite/Database/Beam/Sqlite/Syntax.hs, docs/about/compatibility.md, docs/user-guide/expressions.md
=> Add support for IN predicate and quantified comparisons over lists

CONTRIBUTORS, beam-postgres/beam-postgres.cabal
=> Allow aeson 0.11

CONTRIBUTORS, beam-core/Database/Beam/Backend/SQL/SQL2003.hs, beam-core/Database/Beam/Query/Combinators.hs, beam-postgres/Database/Beam/Postgres/Syntax.hs, docs/about/compatibility.md, docs/user-guide/queries/advanced-features.md, docs/user-guide/queries/ordering.md
https://ronsavage.github.io/SQL/sql-2003-2.bnf.html#null%20ordering
=> Add null ordering

beam-migrate/tools/Migrate.hs
This appears to be a regression in GHC, but I can't for the life of me figure out how to reproduce it.
=> Fix local inference issue with GHC 8.2

beam-core/Database/Beam/Query.hs
=> Export between_

beam-core/Database/Beam/Query/Internal.hs, beam-core/test/Database/Beam/Test/SQL.hs
=> Add Retaggable instance for QGenExpr

beam-core/Database/Beam/Schema/Tables.hs, beam-core/test/Database/Beam/Test/Schema.hs, beam-migrate/Database/Beam/Migrate/Types/CheckedEntities.hs
=> Add support to rename all fields

beam-postgres/Database/Beam/Postgres/Connection.hs
=> Ensure UPDATE/INSERT RETURNING is valid in beam-postgres

beam-core/Database/Beam/Query/SQL92.hs, beam-core/test/Database/Beam/Test/SQL.hs, beam-sqlite/ChangeLog.md, beam-sqlite/beam-sqlite.cabal
=> Correctly generate projection when joining against an ORDER BY over a filtered SELECT

Doc/01-BasicTutorial.lhs
=> Improve hashing of passwords in the tutorial

beam-core/Database/Beam/Backend/SQL/SQL92.hs, beam-core/Database/Beam/Backend/Types.hs, beam-core/beam-core.cabal
=> Added Data.Tagged instances

beam-core/Database/Beam/Query/Internal.hs
Fixes #140 
This is super easy
=> Make QAssignment a Monoid

beam-core/Database/Beam/Query.hs
=> Ignore empty updates

beam-migrate/Database/Beam/Migrate/Generics/Tables.hs
Fixes some of the issues in #132
=> Add default data types for time types

beam-core/Database/Beam/Query.hs, beam-postgres/Database/Beam/Postgres/Connection.hs, beam-postgres/Database/Beam/Postgres/Syntax.hs, beam-sqlite/Database/Beam/Sqlite/Connection.hs
=> More robust support for empty updates/inserts

beam-postgres/Database/Beam/Postgres/Syntax.hs
Referencing: https://github.com/tathougies/beam/issues/152
=> Postgres SELECT ... FOR UPDATE Support

beam-migrate-cli/Database/Beam/Migrate/Tool/Diff.hs, beam-migrate-cli/Database/Beam/Migrate/Tool/SchemaCmd.hs, beam-migrate/Database/Beam/Haskell/Syntax.hs, beam-migrate/Database/Beam/Migrate/Actions.hs, beam-migrate/Database/Beam/Migrate/Simple.hs, beam-migrate/Database/Beam/Migrate/Types.hs, beam-postgres/Database/Beam/Postgres/Extensions.hs
=> Add `createSchema` shortcut

beam-core/Database/Beam/Query/Combinators.hs, beam-core/Database/Beam/Query/Internal.hs, beam-core/Database/Beam/Query/SQL92.hs, beam-postgres/Database/Beam/Postgres/Full.hs, beam-postgres/Database/Beam/Postgres/Syntax.hs, docs/user-guide/backends/beam-postgres.md, docs/user-guide/queries/basic.md
Fixes #152
@SamProtas Let me know what you think of the syntax. I've given some examples in the docs.
=> Implemented locking clause for postgres

.travis.yml, beam-migrate/Database/Beam/Migrate/Log.hs, beam-migrate/Database/Beam/Migrate/SQL/Tables.hs, beam-migrate/Database/Beam/Migrate/Simple.hs, beam-postgres/Database/Beam/Postgres/PgSpecific.hs
=> Be more strict about when to accept notNull

beam-migrate/ChangeLog.md, beam-migrate/Database/Beam/Migrate/Simple.hs, beam-migrate/beam-migrate.cabal
=> Add 'haskellSchema' shortcut

beam-postgres/Database/Beam/Postgres/PgSpecific.hs, docs/beam-templates/employee1out-agg.hs, docs/beam-templates/employee1out.hs, docs/beam-templates/employee1sql-agg.hs, docs/beam-templates/employee1sql.hs, docs/beam-templates/employee2out.hs, docs/beam-templates/employee2sql.hs, docs/beam-templates/employee3common.hs, docs/beam-templates/employee3commonout.hs, docs/beam-templates/employee3commonsql.hs, docs/beam-templates/employee3out-1.hs, docs/beam-templates/employee3out-2.hs, docs/beam-templates/employee3out.hs, docs/beam-templates/employee3sql-1.hs, docs/beam-templates/employee3sql-2.hs, docs/beam-templates/employee3sql.hs, docs/beam.yaml, docs/markdown/beam_query.py, docs/tutorials/tutorial2.md, docs/tutorials/tutorial3.md, docs/user-guide/backends/beam-postgres.md
=> Fix toTsVector and add documentation (plus fixes)

beam-postgres/Database/Beam/Postgres/PgSpecific.hs, stack.yaml
=> Add Semigroup instances for some beam-postgres data structures

beam-core/Database/Beam/Backend/SQL/AST.hs, beam-core/Database/Beam/Backend/SQL/Builder.hs, beam-core/Database/Beam/Backend/SQL/SQL92.hs, beam-core/Database/Beam/Query.hs, beam-postgres/Database/Beam/Postgres/Syntax.hs, beam-sqlite/Database/Beam/Sqlite/Syntax.hs
=> Add aliases on DELETE statements for backends that support it

docs/user-guide/databases.md
Just some documentation fixes.
=> Fix c&p mistake in databases user guide (PersonT -> PostT)

cabal.project
This allows using Cabal's new-* commands.
=> Add a cabal.project file

docs/user-guide/models.md
To reflect the tested code added in 8503c45e118d911b5d158d23f9b25fcc0f3acb37
=> Update the no-primary-key example

beam-core/Database/Beam/Backend/SQL/BeamExtensions.hs, beam-postgres/Database/Beam/Postgres/Connection.hs, beam-postgres/test/Database/Beam/Postgres/Test/DataTypes.hs, beam-postgres/test/Database/Beam/Postgres/Test/Marshal.hs, beam-sqlite/Database/Beam/Sqlite/Connection.hs
This improves composability and consistency with `runSelectReturningList`.
=> Use Sql[Insert,Update,Delete] for MonadBeam[Insert,Update,Delete]Returning

docs/user-guide/expressions.md
I had the problem described in #333 recently and it took me some time to figure it out, a pointer in the docs would have been very helpful.
=> [Docs] Link to #333 for using `in_` with primary keys

beam-sqlite/beam-sqlite.cabal
This make it so this package shows up next to all the other beam packages.
=> Use the Database category in hackage

docs/about/faq.md
By no means a proper comparison but should help place `groundhog` relative to others.
=> Fill in basic information about groundhog

beam-core/Database/Beam/Backend/SQL/BeamExtensions.hs, beam-postgres/Database/Beam/Postgres.hs, beam-postgres/Database/Beam/Postgres/Full.hs, beam-sqlite/Database/Beam/Sqlite/Connection.hs
This removes the need for a lot of annoying type applications.
=> Make BeamHasInsertOnConflict associated types injective

beam-sqlite/beam-sqlite.cabal
=> Add OpenBSD to list of Unix OSs

docs/schema-guide/migrations.md
Just thought this would be an useful addendum for users curious to find out more about this 'pattern'.
=> Link to further details on heterogeneous lists

beam-sqlite/Database/Beam/Sqlite/Migrate.hs
=> Fix detection of DOUBLE (PRECISION) and DECIMAL for sqlite

docs/tutorials/tutorial2.md
IMHO Although the types lead you to be able to rename primary key fields its better to be explicit about it.
=> Clarify how to rename primary key fields.

beam-postgres/Database/Beam/Postgres.hs, beam-postgres/Database/Beam/Postgres/Types.hs
=> Expose utilities for defining FromBackendRow instances for integral types

beam-postgres/Database/Beam/Postgres/Migrate.hs
=> Get db migration backend with schemas

beam-migrate-cli/beam-migrate-cli.cabal, beam-sqlite/beam-sqlite.cabal
=> Loosen version bounds for GHC 8.8

docs/user-guide/queries/relationships.md
=> Fix typo: playlistTrackRelationshipu

beam-postgres/Database/Beam/Postgres/Types.hs
From https://github.com/obsidiansystems/beam/commit/708ad2f8b1f1b5991a019c7a3c1e7ce1dc92f642
=> Add instance HasDefaultDatatype Postgres UTCTime

CONTRIBUTORS
Seems odd not to have one of the maintainers on this list :)
I can add email address too if you want.
=> Add Ken Micklas to CONTRIBUTORS

beam-migrate/Database/Beam/Migrate/SQL/Tables.hs, beam-migrate/Database/Beam/Migrate/Types/CheckedEntities.hs, beam-migrate/Database/Beam/Migrate/Types/Predicates.hs, beam-sqlite/beam-sqlite.cabal, beam-sqlite/test/Database/Beam/Sqlite/Test/Migrate.hs, beam-sqlite/test/Main.hs
=> Suppress creation of primary key constraints for tables with no primary key

release.nix
=> Use haskell-src-exts 1.23.0 in CI for GHC 8.8

.gitlab-ci.yml, beam-core/beam-core.cabal, beam-migrate-cli/beam-migrate-cli.cabal, beam-migrate/beam-migrate.cabal, beam-postgres/Database/Beam/Postgres/Types.hs, beam-postgres/beam-postgres.cabal, beam-postgres/test/Database/Beam/Postgres/Test/DataTypes.hs, beam-sqlite/beam-sqlite.cabal, docs/about/license.md, docs/index.md, docs/tutorials/tutorial1.md, docs/tutorials/tutorial3.md, docs/user-guide/custom-type-migration.md, docs/user-guide/models.md, mkdocs.yml
=> Fix up tathougies -> haskell-beam at a bunch of places

beam-core/beam-core.cabal, beam-migrate-cli/beam-migrate-cli.cabal, beam-migrate/beam-migrate.cabal, beam-postgres/Database/Beam/Postgres/Types.hs, beam-postgres/beam-postgres.cabal, beam-postgres/test/Database/Beam/Postgres/Test/DataTypes.hs, beam-sqlite/beam-sqlite.cabal, docs/about/license.md, docs/index.md, docs/tutorials/tutorial1.md, docs/tutorials/tutorial3.md, docs/user-guide/custom-type-migration.md, docs/user-guide/models.md, mkdocs.yml
Just updating the links in various modules to reflect the new GitHub organization.
=> Update links in various modules and documentation

docs/beam-templates/employee2out.hs, docs/beam-templates/employee2sql.hs, docs/beam-templates/employee3common.hs, docs/tutorials/tutorial1.md, docs/tutorials/tutorial2.md, docs/tutorials/tutorial3.md, docs/user-guide/custom-type-migration.md, docs/user-guide/databases.md, docs/user-guide/expressions.md, docs/user-guide/manipulation/update.md, docs/user-guide/models.md, docs/user-guide/queries/advanced-features.md, docs/user-guide/queries/aggregates.md, docs/user-guide/queries/basic.md, docs/user-guide/queries/common-table-expressions.md, docs/user-guide/queries/window-functions.md
=> Use explicitly sized integers in docs

beam-sqlite/beam-sqlite.cabal, beam-sqlite/test/Database/Beam/Sqlite/Test.hs, beam-sqlite/test/Database/Beam/Sqlite/Test/Migrate.hs, beam-sqlite/test/Database/Beam/Sqlite/Test/Select.hs, beam-sqlite/test/Main.hs
This adds a test for the known bug documented in #326.
=> Add failing test for EXCEPT with VALUES in SQLite

docs.nix, nixpkgs/pinned.nix, release.nix
This is per @3noch's suggestion
=> Fix nixpkgs pinning

beam-core/ChangeLog.md, beam-migrate/ChangeLog.md, beam-postgres/ChangeLog.md, beam-sqlite/ChangeLog.md
Rendered:
* [beam-core](https://github.com/kmicklas/beam/blob/release-notes/beam-core/ChangeLog.md)
* [beam-migrate](https://github.com/kmicklas/beam/blob/release-notes/beam-migrate/ChangeLog.md)
* [beam-postgres](https://github.com/kmicklas/beam/blob/release-notes/beam-postgres/ChangeLog.md)
* [beam-sqlite](https://github.com/kmicklas/beam/blob/release-notes/beam-sqlite/ChangeLog.md)
=> Add tentative ChangeLog entries

beam-postgres/ChangeLog.md
Unfortunately this note won't be in the official release distribution which includes #520, but adding it to master for posterity.
=> Add beam-postgres ChangeLog entry for #520

beam-core/beam-core.cabal, beam-migrate-cli/beam-migrate-cli.cabal, beam-migrate/beam-migrate.cabal, beam-postgres/beam-postgres.cabal, beam-sqlite/beam-sqlite.cabal
=> Loosen version bounds on aeson

.github/workflows/build.yaml
=> Upgrade install-nix-action and cachix-action

beam-postgres/Database/Beam/Postgres/PgSpecific.hs, beam-postgres/test/Database/Beam/Postgres/Test/Select.hs
=> Remove invalid parentheses emitted by pgUnnest

beam-core/ChangeLog.md, beam-core/Database/Beam/Query/Combinators.hs, beam-core/Database/Beam/Query/CustomSQL.hs, beam-core/Database/Beam/Schema/Tables.hs, beam-migrate/Database/Beam/Migrate.hs, beam-sqlite/Database/Beam/Sqlite/Connection.hs, docs/user-guide/models.md, docs/user-guide/queries/aggregates.md
Found these way back when first reading the user guide then forgot to PR for two years
=> Fix several typos

docs/user-guide/expressions.md
=> Docs: subquery_

beam-core/Database/Beam/Backend/SQL/Row.hs, beam-core/beam-core.cabal, beam-migrate/Database/Beam/Migrate/Actions.hs, beam-migrate/beam-migrate.cabal, beam-postgres/Database/Beam/Postgres/Connection.hs, beam-postgres/Database/Beam/Postgres/Full.hs, beam-postgres/test/Database/Beam/Postgres/Test/Select.hs
I'm working on adding GHC 9.0 to CI in a separate PR, but these are the required code changes.
=> Support GHC 9.0

beam-core/beam-core.cabal, beam-sqlite/beam-sqlite.cabal
=> Loosen bounds for dlist 1.0

beam-core/beam-core.cabal, nix/lib.nix
=> Support vector-sized 1.5

beam-sqlite/Database/Beam/Sqlite/Syntax.hs, beam-sqlite/beam-sqlite.cabal, beam-sqlite/test/Database/Beam/Sqlite/Test/Insert.hs, beam-sqlite/test/Database/Beam/Sqlite/Test/Select.hs, beam-sqlite/test/Main.hs
=> Support inserting all default values in SQLite

docs/default.nix, docs/user-guide/expressions.md
This is a prerequisite to #612.
=> Fix docs examples and verify in CI

beam-core/beam-core.cabal
=> beam-core: Prevent compilation with GHC < 8.4

beam-core/ChangeLog.md, beam-core/beam-core.cabal, beam-migrate/ChangeLog.md, beam-migrate/beam-migrate.cabal, beam-postgres/ChangeLog.md, beam-postgres/beam-postgres.cabal, beam-sqlite/ChangeLog.md, beam-sqlite/beam-sqlite.cabal
=> Minor releases to support Aeson 2.0

docs/tutorials/tutorial3.md
=> Update link to deprecated package in tutorial

beam-core/Database/Beam/Backend/SQL/AST.hs, beam-core/Database/Beam/Backend/SQL/Builder.hs, beam-core/Database/Beam/Backend/SQL/SQL92.hs, beam-core/Database/Beam/Query.hs, beam-core/Database/Beam/Query/Ord.hs, beam-core/beam-core.cabal, beam-migrate-cli/beam-migrate-cli.cabal, beam-migrate/Database/Beam/Haskell/Syntax.hs, beam-migrate/beam-migrate.cabal, beam-postgres/Database/Beam/Postgres/Syntax.hs, beam-postgres/beam-postgres.cabal, beam-postgres/test/Database/Beam/Postgres/Test/Select.hs, beam-sqlite/Database/Beam/Sqlite/Syntax.hs, beam-sqlite/beam-sqlite.cabal, beam-sqlite/test/Database/Beam/Sqlite/Test/Select.hs
This is some basic functionality that's been missing for a while.
=> `IN (SELECT ...)` syntax for beam

beam-sqlite/Database/Beam/Sqlite/Syntax.hs, beam-sqlite/test/Database/Beam/Sqlite/Test/Insert.hs
=> Add failing test for UTCTime years

beam-core/Database/Beam/Query/Combinators.hs, beam-core/Database/Beam/Query/Internal.hs, beam-core/Database/Beam/Query/SQL92.hs, beam-postgres/Database/Beam/Postgres/Full.hs
=> Make sure lateral join names do not overlap

docs/default.nix, release.nix, shell.nix
=> Nix fixes from #650

beam-core/ChangeLog.md, beam-migrate/ChangeLog.md, beam-postgres/ChangeLog.md, beam-sqlite/ChangeLog.md
In preparation for a new release.
=> Add missing changelogs for 0.10.0.0

beam-core/beam-core.cabal, beam-migrate/beam-migrate.cabal, beam-postgres/beam-postgres.cabal, nix/lib.nix
=> Loosen bounds on vector

beam-core/ChangeLog.md, beam-migrate/ChangeLog.md, beam-migrate/beam-migrate.cabal, beam-postgres/ChangeLog.md, beam-postgres/beam-postgres.cabal, beam-sqlite/ChangeLog.md, beam-sqlite/beam-sqlite.cabal
* https://hackage.haskell.org/package/beam-core-0.10.1.0
* https://hackage.haskell.org/package/beam-migrate-0.5.2.1
* https://hackage.haskell.org/package/beam-postgres-0.5.3.1
* https://hackage.haskell.org/package/beam-sqlite-0.5.3.0
=> Add changelog for v0.10.1.0 and associated releases

.gitignore, beam-migrate/Database/Beam/Migrate/Backend.hs, beam-migrate/Database/Beam/Migrate/Serialization.hs, beam-postgres/Database/Beam/Postgres/Migrate.hs, beam-sqlite/Database/Beam/Sqlite/Migrate.hs
I'd like this in the 0.11 release, so I can release https://github.com/f-omega/beam-migrate-cli on hackage.
=> Merge migration changes into 0.11
